name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Fetch source code
        uses:
          actions/checkout@v2
          # - name: Login to Docker Hub
          #      uses: docker/login-action@v1
          #   with:
          #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
          #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          # -
          #   name: Set up Docker Buildx
          #   uses: docker/setup-buildx-action@v1
          # -
          #   name: Build and push
          #   uses: docker/build-push-action@v2
          #   with:
          #     context: .
          #     file: ./Dockerfile
          #     push: true
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
      - name: Run Rust tests
        run: nix-shell --run 'MONGO_URI="mongodb://127.0.0.1:27017" cargo test'
